# Generated by Django 3.2.5 on 2021-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attchment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
