# Generated by Django 3.2.5 on 2021-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210823_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attchment',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
